site_name: Keras中文文档
pages:
- ['index.md','主页']
- ['getting_started/concepts.md','快速开始','一些基本概念']
- ['getting_started/install.md','快速开始','Keras安装和配置指南']
- ['getting_started/sequential_model.md','快速开始','快速开始Sequential模型']
- ['getting_started/functional_API.md','快速开始','快速开始泛型模型']
- ['getting_started/FAQ.md','快速开始','FAQ']
- ['models/about_model.md','模型','关于Keras模型']
- ['models/sequential.md','模型','Sequential模型']
- ['models/model.md','模型','泛型模型']
- ['layers/about_layer.md','网络层','关于Keras层']
- ['layers/core_layer.md','网络层','常用层Core']
- ['layers/convolutional_layer.md','网络层','卷积层Convolutional']
- ['layers/recurrent_layer.md','网络层','递归层Recurrent']
- ['layers/embedding_layer.md','网络层','嵌入层Embedding']
- ['layers/advanced_activation_layer.md','网络层','高级激活层Advanced Activation']
- ['layers/normalization_layer.md','网络层','规范层BatchNormalization']
- ['layers/noise_layer.md','网络层','噪声层Noise']
- ['layers/wrapper.md','网络层','包装器Wrapper']
- ['layers/writting_layer.md','网络层','编写自己的层']
- ['preprocessing/sequence.md','预处理','序列预处理']
- ['preprocessing/text.md','预处理','文本预处理']
- ['preprocessing/image.md','预处理','图片预处理']
- ['other/objectives.md','其他重要模块','目标函数Objective']
- ['other/optimizers.md','其他重要模块','优化器Optimizer']
- ['other/activations.md','其他重要模块','激活函数Activation']
- ['other/callbacks.md','其他重要模块','回调函数Callback']
- ['other/initializations.md','其他重要模块','初始化方法Initialization']
- ['other/regularizers.md','其他重要模块','正则项Regularizer']
- ['other/constraints.md','其他重要模块','约束项Constraint']
- ['other/datasets.md','其他重要模块','常用数据库Dataset']
- ['other/visualization.md','其他重要模块','可视化Visualization']
- ['backend.md','keras后端Backend']
- ['scikit-learn_API.md','scikit-learn接口']
- ['blog/cnn_see_world.md','深度学习与Keras','CNN眼中的世界']
- ['blog/autoencoder.md','深度学习与Keras','花式自动编码器']
- ['blog/image_classification_using_very_little_data.md','深度学习与Keras','面向小数据集构建图像分类模型']
- ['acknowledgement.md','致谢']
theme: readthedocs
site_author: BigMoyan
